apiVersion: v1
kind: Service
metadata:
  name: ci-cd-demo-app
  namespace: default
  labels:
    app: ci-cd-demo-app
    managed-by: ci-cd-pipeline
spec:
  type: ClusterIP
  selector:
    app: ci-cd-demo-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
